/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class src_BlackjackNative */

#ifndef _Included_src_BlackjackNative
#define _Included_src_BlackjackNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     src_BlackjackNative
 * Method:    createGameInstance
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_src_BlackjackNative_createGameInstance
  (JNIEnv *, jobject);

/*
 * Class:     src_BlackjackNative
 * Method:    destroyGameInstance
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_src_BlackjackNative_destroyGameInstance
  (JNIEnv *, jobject, jlong);

/*
 * Class:     src_BlackjackNative
 * Method:    newGame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_src_BlackjackNative_newGame
  (JNIEnv *, jobject);

/*
 * Class:     src_BlackjackNative
 * Method:    placeBet
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_src_BlackjackNative_placeBet
  (JNIEnv *, jobject, jint);

/*
 * Class:     src_BlackjackNative
 * Method:    playerHit
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_src_BlackjackNative_playerHit
  (JNIEnv *, jobject);

/*
 * Class:     src_BlackjackNative
 * Method:    playerStand
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_src_BlackjackNative_playerStand
  (JNIEnv *, jobject);

/*
 * Class:     src_BlackjackNative
 * Method:    isGameOver
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_src_BlackjackNative_isGameOver
  (JNIEnv *, jobject);

/*
 * Class:     src_BlackjackNative
 * Method:    getPlayerCards
 * Signature: ()[Lsrc/Card;
 */
JNIEXPORT jobjectArray JNICALL Java_src_BlackjackNative_getPlayerCards
  (JNIEnv *, jobject);

/*
 * Class:     src_BlackjackNative
 * Method:    getDealerCards
 * Signature: ()[Lsrc/Card;
 */
JNIEXPORT jobjectArray JNICALL Java_src_BlackjackNative_getDealerCards
  (JNIEnv *, jobject);

/*
 * Class:     src_BlackjackNative
 * Method:    shouldHideDealerFirstCard
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_src_BlackjackNative_shouldHideDealerFirstCard
  (JNIEnv *, jobject);

/*
 * Class:     src_BlackjackNative
 * Method:    getPlayerMoney
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_src_BlackjackNative_getPlayerMoney
  (JNIEnv *, jobject);

/*
 * Class:     src_BlackjackNative
 * Method:    getCurrentBet
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_src_BlackjackNative_getCurrentBet
  (JNIEnv *, jobject);

/*
 * Class:     src_BlackjackNative
 * Method:    getPlayerHandValue
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_src_BlackjackNative_getPlayerHandValue
  (JNIEnv *, jobject);

/*
 * Class:     src_BlackjackNative
 * Method:    getDealerHandValue
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_src_BlackjackNative_getDealerHandValue
  (JNIEnv *, jobject);

/*
 * Class:     src_BlackjackNative
 * Method:    didPlayerWin
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_src_BlackjackNative_didPlayerWin
  (JNIEnv *, jobject);

/*
 * Class:     src_BlackjackNative
 * Method:    didDealerWin
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_src_BlackjackNative_didDealerWin
  (JNIEnv *, jobject);

/*
 * Class:     src_BlackjackNative
 * Method:    isTie
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_src_BlackjackNative_isTie
  (JNIEnv *, jobject);

/*
 * Class:     src_BlackjackNative
 * Method:    getGameStateMessage
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_src_BlackjackNative_getGameStateMessage
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
